### ISSUE TITLE
Need to document (or find a solution to) the fact that classes need to implement toJson to be returned in controllers

### ISSUE THREAD

**Issue by bradcypert** [PyreStudios/steward#13]
Example stacktrace:

```
Converting object to an encodable object failed: Instance of 'Lesson'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:688:7)
#1      _JsonStringifier.writeList (dart:convert/json.dart:736:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:718:7)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
#6      JsonEncoder.convert (dart:convert/json.dart:262:30)
#7      JsonCodec.encode (dart:convert/json.dart:172:45)
#8      jsonEncode (dart:convert/json.dart:81:10)
#9      writeResponse (package:steward/router/response.dart:66:18)
<asynchronous suspension>
#10     Router.serveHTTP (package:steward/router/router.dart:155:13)
<asynchronous suspension>
#11     App.start (package:steward/app/app.dart:22:12)
<asynchronous suspension>
```

example class:

```dart
import 'package:uuid/uuid.dart';

class Lesson {
  String? uuid;
  String title;
  String? lessonImage;
  String content;
  String? workshopUuid;

  Lesson(
      {required this.title,
      required this.content,
      this.lessonImage,
      this.uuid,
      this.workshopUuid}) {
    uuid ??= Uuid().v4();
  }
}
```

Example solution:

```dart
import 'package:uuid/uuid.dart';

class Lesson {
  String? uuid;
  String title;
  String? lessonImage;
  String content;
  String? workshopUuid;

  Lesson(
      {required this.title,
      required this.content,
      this.lessonImage,
      this.uuid,
      this.workshopUuid}) {
    uuid ??= Uuid().v4();
  }

  toJson() {
    return {
      'uuid': uuid,
      'title': title,
      'lessonImage': lessonImage,
      'content': content,
      'workshopUuid': workshopUuid
    };
  }
}
```

Honestly, we could probably derive the toJson method based on the fields at runtime via reflection but then we get into a whole bag of worms about hiding fields and other problems. It might just be easier to find a way to make sure things implement toJson.

**Comment by bradcypert** [comment]
Food for thought: Since we're leveraging reflection already, can we generate this for simple classes? For example, if all the properties are primitives, can we build this on the fly? Alternatively, we can try to convert classes into a map (reflectively, too) since json Encoding works on maps, too.

**Comment by mdb2301** [comment]
Maybe you are looking for [this](https://pub.dev/packages/json_serializable)?

**Comment by bradcypert** [comment]
I don't necessarily want to dictate that people use JsonSerializable, though that does work as a solution for making a class serializable.

The issue here is that if you return a type from your controller handler, it needs to have a toJson method. At this moment, I don't have a typesafe way to indicate that you must include a toJson method, and I think a lot of this is stemming from how flexible the return type of the handler (dynamic) truly is.

You've got me thinking more about this though and I suppose that I could look at an intermediate type (we have one currently called Response), or I could look at identifying a shared method for all of those types and requiring that via an interface.

**Comment by bradcypert** [comment]
My original comment about reflection is a non-starter for me. I am hoping by and large for static metaprogramming in Dart. There is an issue for it, and it will effectively give me a much more typesafe replacement for all of my reflection-based workings thus far. However, the intermediate type that I mentioned above could also solve this particular reflection-based issue, too.

**Comment by bradcypert** [comment]
Removing reflection forced me to solve this.
